@startuml
title Flowchart Personal Website

start
:User membuka Home (index.html);
:Menampilkan keterangan singkat tentang pemilik website;
:Menampilkan 3 informasi umum;
-> Roblox;
if (User pilih Roblox?) then (ya)
    :Menampilkan informasi:\n- Cara dapat item gratis\n- Membuat karakter/avatar\n- Harga item dan hyperlink ke item;
elseif (User pilih Mobile Legend?) then (ya)
    :Menampilkan informasi:\n- Role & Hero yang dimainkan\n- Tutorial hero\n- Hyperlink ke tutorial;
elseif (User pilih GitHub?) then (ya)
    :Menampilkan informasi:\n- Bahasa pemrograman yang dipelajari\n- Hyperlink ke repositori terkait;
else
    :User tetap di halaman Home;
endif
stop

@enduml
